models/product.py
from sqlalchemy import Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from orm.setting import db


class Product(db.Model):
    id: Mapped[int] = mapped_column(Integer, autoincrement=True, primary_key=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(String)
    price: Mapped[int] = mapped_column(Integer, nullable=False)

app.py
from flask import Flask
from orm.setting import db
from flask_migrate import Migrate
from views.products import products_bp

# create the app
app = Flask(__name__)
app.register_blueprint(products_bp)
# configure the SQLite database, relative to the app instance folder
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"
# initialize the app with the extension
db.init_app(app)
Migrate(app, db)


if __name__ == "__main__":
    app.run(port=3456, debug=True)

views/products.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.product import Product
from orm.setting import db

products_bp = Blueprint("products", __name__)


@products_bp.route("/")
def index():
    products = Product.query.order_by(Product.id.desc())
    return render_template("products/index.jinja", products=products)


@products_bp.route("/add", methods=["GET", "POST"])
def add():
    if request.method == "POST":
        title = request.form["title"]
        description = request.form["description"]
        price = request.form["price"]
        product = Product(title=title, description=description, price=price)

        db.session.add(product)
        db.session.commit()

        return redirect(url_for("products.index"))

    return render_template("products/add.jinja")


@products_bp.route("/<int:id>", methods=["GET", "POST"])
def each(id):
    product = Product.query.get_or_404(id)
    if request.method == "POST":

        db.session.delete(product)
        db.session.commit()

        return redirect(url_for("products.index"))

    return render_template("products/each.jinja", product=product)


@products_bp.route("/<int:id>/edit", methods=["GET", "POST"])
def edit(id):
    product = Product.query.get_or_404(id)
    if request.method == "POST":
        product.title = request.form["title"]
        product.description = request.form["description"]
        product.price = request.form["price"]

        db.session.add(product)
        db.session.commit()

        return redirect(url_for("products.each", id=product.id))

    return render_template("products/edit.jinja", product=product)

templates/layouts/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

templates/products/add.jinja
{% extends "layouts/base.jinja" %}

{% block content %}
<h1>商品列表</h1>
<form method="POST" action="{{ url_for('products.add') }}">
    <label for="title">品名</label>
    <input type="text" name="title">

    <label for="description">商品描述</label>
    <textarea name="description"></textarea>

    <label for="price">價格</label>
    <input type="number" name="price">

    <button type="submit">增新</button>
</form>
{% endblock content %}

templates/products/each.jinja
{% extends "layouts/base.jinja" %}

{% block content %}
<h1>{{product.title}}</h1>
<p>{{ product.price}}</p>
<p>{{product.description | striptags}}</p>

<a href="{{ url_for('products.edit', id=product.id)}}">編輯商品</a>

<form method="POST" action="{{ url_for('products.each', id=product.id) }}">
    <button type="submit">刪除商品</button>
</form>

<a href="{{ url_for('products.index')}}">返回首頁</a>

{% endblock content %}

templates/products/edit.jinja
{% extends "layouts/base.jinja" %}

{% block content %}
<h1>商品列表</h1>
<form method="POST" action="{{ url_for('products.edit', id=product.id) }}">
    <label for="title">品名</label>
    <input type="text" name="title" value="{{ product.title }}">

    <label for="description">商品描述</label>
    <textarea name="description">{{ product.description}}</textarea>

    <label for="price">價格</label>
    <input type="number" name="price" value="{{ product.price }}">

    <button type="submit">確定</button>
</form>

<a href="{{ url_for('products.each', id=product.id) }}">編輯</a>
{% endblock content %}

templates/products/index.jinja
{% extends "layouts/base.jinja" %}

{% block content %}
<h1>商品列表</h1>
<ul>
    {% for product in products  %}
    <li>
        <a href="{{ url_for('products.each', id=product.id) }}">
            <h3>{{product.title}}</h3>
            <p>{{ product.description | striptags | truncate(50) }}</p>
            <p>{{ product.price}}</p>
        </a>
    </li>
    {% endfor %}
    <a href="{{url_for('products.add')}}">增新商品</a>
</ul>
{% endblock content %}